name: Deploy Production

on:
  workflow_dispatch:
  push:
    branches: [main]

env:
  CI: true
  BUCKET_ID: ${{ secrets.BUCKET_ID }}
  CALCULATOR_ONLINE_DIST: ${{ secrets.CALCULATOR_ONLINE_DIST }}
  CALCULATOR_OFFLINE_DIST: ${{ secrets.CALCULATOR_OFFLINE_DIST }}
  DOCUMENTATION_DIST: ${{ secrets.DOCUMENTATION_DIST }}

jobs:
  deploy_calculator_online:
    name: Deploy Calculator Online Version
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run test:number-cruncher && npm run build:calculator
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1
    - name: Deploy static site to S3 bucket
      run: aws s3 sync ./apps/calculator/build s3://$BUCKET_ID/calculator/online/ --delete
    - name: Invalidate Cloundfront distrubution
      run: aws cloudfront create-invalidation --distribution-id $CALCULATOR_ONLINE_DIST --paths '/*'

  deploy_online_version:
    name: Deploy Documentation
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build:documentation
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1
    - name: Deploy static site to S3 bucket
      run: aws s3 sync ./apps/documentation/build s3://$BUCKET_ID/documentation --delete
    - name: Invalidate Cloundfront distrubution
      run: aws cloudfront create-invalidation --distribution-id $DOCUMENTATION_DIST --paths '/*'

  deploy_calculator_offline:
    name: Deploy Calculator Offline Version
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with: 
        fetch-depth: 0
    - name: Configure offline mode
      run: |
        sed -i 's/"homepage": "\/"/"homepage": ".\/"/g' apps/calculator/package.json
    - name: Install dependencies
      run: npm ci
    - name: Build
      env:
        REACT_APP_OFFLINE_MODE: true
      run: npm run test:number-cruncher && npm run build:calculator
    - name: Zip
      run: |
        mkdir deploy
        zip -r deploy/$(node -pe "require('./apps/calculator/package.json')['version']").zip apps/calculator/build
    - name: Setup Vars
      id: vars
      run: |
        VERSION_NUMBER=$(node -pe "require('./apps/calculator/package.json')['version']") 
        echo ::set-output name=release_tag::v$VERSION_NUMBER
        echo ::set-output name=release_name::Arithmico v$VERSION_NUMBER
        echo ::set-output name=release_text::"Download offline version [here](https://blob.arithmico.com/arithmico-calculator/$(echo $VERSION_NUMBER).zip)"
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ steps.vars.outputs.release_tag }}
        release_name: ${{ steps.vars.outputs.release_name }}
        body: ${{ steps.vars.outputs.release_text }}
        draft: false
        prerelease: false

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1
    - name: Deploy static site to S3 bucket
      run: aws s3 sync ./deploy/ s3://$BUCKET_ID/blob/calculator/offline/
    - name: Invalidate Cloundfront distrubution
      run: aws cloudfront create-invalidation --distribution-id $CALCULATOR_OFFLINE_DIST --paths '/*'
